export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#2f3b88",
        "surface-container-high": "#dde9ff",
        "secondary-fixed": "#6ffbbe",
        "surface-tint": "#4c58a6",
        "on-primary-fixed-variant": "#343f8d",
        "surface-dim": "#ccdbf4",
        "surface-container-low": "#eff4ff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "background": "#f8f9ff",
        "error": "#ba1a1a",
        "surface-container-highest": "#d5e3fd",
        "inverse-primary": "#bbc3ff",
        "on-secondary-container": "#00714d",
        "surface-variant": "#d5e3fd",
        "on-surface-variant": "#454652",
        "outline-variant": "#c5c5d4",
        "on-background": "#0d1c2f",
        "on-secondary-fixed": "#002113",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005236",
        "primary-container": "#4854a2",
        "secondary": "#006c49",
        "tertiary-fixed": "#ffddb8",
        "tertiary-container": "#805000",
        "on-primary-container": "#cacfff",
        "tertiary-fixed-dim": "#ffb95f",
        "inverse-surface": "#233144",
        "on-error": "#ffffff",
        "primary-fixed": "#dfe0ff",
        "secondary-fixed-dim": "#4edea3",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0d1c2f",
        "primary-fixed-dim": "#bbc3ff",
        "surface": "#f8f9ff",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9ff",
        "inverse-on-surface": "#ebf1ff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#2a1700",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#000e5f",
        "on-tertiary-fixed-variant": "#653e00",
        "outline": "#757684",
        "surface-container": "#e6eeff",
        "tertiary": "#603b00",
        "on-tertiary-container": "#ffc988"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
